stages:
- lint
- pytest
- test
- Test_Build
- Deploy_to_PyPi

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


license_scanning:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

.lint:
  stage: lint
  before_script:
    - pip install -U pip
    - pip install --cache-dir=~/.cache/pip/ -r requirements-dev.txt --quiet
  script:
    - pylint ./pddns
    - flake8 ./pddns
    - bandit -r ./pddns
    - black --check ./pddns
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.cache/pip/

python-3.6-lint:
  extends: ".lint"
  image: python:3.6

python-3.7-lint:
  extends: ".lint"
  image: python:3.7

python-3.8-lint:
  extends: ".lint"
  image: python:3.8

python-3.9-lint:
  extends: ".lint"
  image: python:3.9

pytest:
  image: python:3.8
  stage: pytest
  before_script:
    - pip install -U pip
    - pip install --cache-dir=~/.cache/pip/ -r requirements-dev.txt --quiet
  script:
    - pytest ./pddns


.build:
 stage: test
 artifacts:
   paths:
     - dist/
 before_script:
  - pip install -U setuptools twine --quiet
  - pip install -r requirements.txt
 script:
   - python setup.py sdist bdist_wheel
   - python -m twine check dist/*

python-3.6-build:
  extends: ".build"
  image: python:3.6

python-3.7-build:
  extends: ".build"
  image: python:3.7

python-3.8-build:
  extends: ".build"
  image: python:3.8

python-3.9-build:
  extends: ".build"
  image: python:3.9

.test:
  stage: Test_Build
  before_script:
    - pip install -U pip
  script:
    - pip install dist/*.whl
    - pip show -f python_ddns
    - command -v pddns
    - pddns -i -d
    - pddns -t -d

python-3.6-test:
  extends: ".test"
  image: python:3.6

python-3.7-test:
  extends: ".test"
  image: python:3.7

python-3.8-test:
  extends: ".test"
  image: python:3.8

python-3.9-test:
  extends: ".test"
  image: python:3.9

Deploy_to_PyPi:
  image: python:3.8
  stage: Deploy_to_PyPi
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  before_script:
    - pip install -U pip setuptools twine --quiet
  script:
    - twine upload --verbose dist/* --username $PRODUCTION_USER --password $PRODUCTION_PASSWORD
    - twine upload --verbose dist/* --repository-url https://push.fury.io/cyb3r-jak3 --username $GEM_TOKEN --password ""
  only:
    refs:
      - tags
      - master
    variables:
      - $CI_COMMIT_TAG

